__all__ = ('PREPEND_LOC_URL_WITH_SITE_URL', 'PREPEND_IMAGE_LOC_URL_WITH_SITE_URL')

from qartez.conf import get_setting

PREPEND_LOC_URL_WITH_SITE_URL = get_setting('PREPEND_LOC_URL_WITH_SITE_URL')
PREPEND_IMAGE_LOC_URL_WITH_SITE_URL = get_setting('PREPEND_IMAGE_LOC_URL_WITH_SITE_URL')
DEBUG = get_setting('DEBUG')
